WORS_Loot_Boss_Data = {
    ["Kalphite Queen"] = {
        "Monkfish",
        "Shark",
        "Dark crab",
        "Saradomin brew(4)",
        "Prayer potion(4)",
        "Super restore(4)",
        "Super combat potion(2)",
        "Ranging potion(3)",
        "Superantipoison(2)",
        "Rune chainbody",
        "Red d'hide body",
        "Rune knife(p++)",
        "Lava battlestaff",
        "Death Rune",
        "Blood Rune",
        "Mithril arrow",
        "Rune arrow",
        "Grimy toadflax",
        "Grimy ranarr weed",
        "Grimy snapdragon",
        "Grimy torstol",
        "Torstol seed",
        "Watermelon seed",
        "Papaya tree seed",
        "Palm tree seed",
        "Magic seed",
        "Runite bar",
        "Bucket of sand",
        "Gold ore",
        "Magic logs",
        "Uncut emerald",
        "Uncut ruby",
        "Uncut diamond",
        "Wine of zamorak",
        "Potato cactus",
        "Coins",
        "Grapes",
        "Weapon poison(++)",
        "Cactus spine",
    },
    ["King Black Dragon"] = {
        "Dragon bones",
        "Black dragonhide",
        "Dragon pickaxe",
        "Rune longsword",
        "Adamant platebody",
        "Adamant kiteshield",
        "Dragon med helm",
        -- You can add more items if necessary
    },
}
